name: Deployment


on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  Testing:
    name: Testing the project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installing the necessary depenedencies
        run: npm install

      - name: Test cases run
        run: npm test 

  Deploying:
    name: Deploying to github pages
    runs-on: ubuntu-latest

    needs: Testing

    steps:
        - uses: actions/checkout@v2

        - name: Installing the necessary depenedencies
          run: npm install

        - name: Running build and deploy
          run: npm run deploy        
          env:
            CI: false